[package]
name = "demoinfocs-proto"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
prost = "0.12"

[build-dependencies]
prost-build = "0.12"
sevenz-rust = "0.6"
reqwest = { version = "0.12", features = ["blocking"] }
