@startuml
participant Consumer
participant Parser
participant Queue

note over Consumer, Parser
Multiple demos can be processed concurrently using
`utils::parallel::run` together with Rayon.
end note

Consumer ++
Consumer -> Parser ++: ParseToEnd
par
    loop parsing loop
        Parser -> Parser ++: parseFrame
        Parser -> Queue ++: enqueue net-msg
        Parser --
    end
    Parser --

    else

    loop processing loop
        Queue --> Parser --: receive net-msg
        Parser ++
        Parser -> Parser ++: process
        Parser -> Consumer ++: call EventHandler
        Consumer --> Parser --
        Parser --
    end
end
Parser -> Consumer --
Consumer --

@enduml