name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Format
        run: cargo fmt --manifest-path demoinfocs-rs/Cargo.toml -- --check

      - name: Clippy
        run: cargo clippy --manifest-path demoinfocs-rs/Cargo.toml -- -D warnings

      - name: Build examples
        run: cargo build --manifest-path demoinfocs-rs/Cargo.toml --examples

      - name: Test
        run: cargo test --manifest-path demoinfocs-rs/Cargo.toml

